import "./globals.css";

export const metadata = {
    title: "Usuarios com getbyid",
    description: "Generated by create next app",
    icons: {
        icon: "/icons/favicon.ico",
    },
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>{children}</body>
        </html>
    );
}

